FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential pkg-config automake libtool libasound2-dev wget unzip

ADD . /repo
WORKDIR /repo
RUN ./dependencies.sh
RUN ./autogen.sh
RUN ./configure
RUN make -j8
